### ISSUE TITLE
what is purpose of `from keras.datasets import mnist` in the ipnb?

### ISSUE THREAD

**Issue by StanSilas** [manashmndl/DeadSimpleSpeechRecognizer#1]
I am a new practitioner of speech processing.
i am confused as why you did `from keras.datasets import mnist` in the .ipynb
 when the data we are concerned with is an audio file.
 
Also if you notice here :
 https://blog.manash.me/building-a-dead-simple-word-recognition-engine-using-convnet-in-keras-25e72c19c12b  the first three code blocks , i,e

https://gist.githubusercontent.com/manashmndl/e24dbe21f2addc3e02748ec81db27999/raw/fb32fd606ed6f9cd4aed3d4175cadd8652613d70/mfcc.py  

https://gist.githubusercontent.com/manashmndl/7662224549b97757f47502577d6a4b5e/raw/bb239ce578bc0436a30dd60e07905d0fe2b2bdba/get_labels.py 

are not present in the ipynb here : https://github.com/manashmndl/DeadSimpleSpeechRecognizer/blob/master/SpeechRecognition.ipynb
So, i'm confused how it is still working.

Request you to kindly update the IPYNB to include an end to end tutorial.

Thank you.

**Comment by manashmandal** [comment]
Sorry I was just running some random experiments with the codes. You are right, it doesn't have to do anything with recognizing speech. I'll clean up the code as soon as possible. Thanks!
