### ISSUE TITLE
Which tutorial is to follow ?

### ISSUE THREAD

**Issue by manbharae** [manashmndl/DeadSimpleSpeechRecognizer#3]
Sir, I'm new to speech and audio processing. 
I am confused, whether https://blog.manash.me/building-a-dead-simple-word-recognition-engine-using-convnet-in-keras-25e72c19c12b  is more accurate (end -end) or the ipynb here https://github.com/manashmndl/DeadSimpleSpeechRecognizer/blob/master/SpeechRecognition.ipynb?

Request to make clean ipynb for new bies like me. 
Thanks for share your knowledge.

**Comment by manashmandal** [comment]
http://nbviewer.jupyter.org/github/manashmndl/DeadSimpleSpeechRecognizer/blob/master/DeadSimpleSpeechRecognition.ipynb

Check this, I have updated the notebook.
