### ISSUE TITLE
incomplete tutorial

### ISSUE THREAD

**Issue by manbharae** [manashmndl/DeadSimpleSpeechRecognizer#4]
Sir there many missing code in ipynb and there is not complete code on your blog. 
Very nice tutorial for read , but hard for me to execute on my end. 

Please Please include all steps in ipynb , as many steps missing. 
Sincerely thanks

**Comment by manashmandal** [comment]
Will do

**Comment by manbharae** [comment]
Thank you Sir, I will be eagerly waiting and look forward to learning from more your tutorials.

**Comment by manashmandal** [comment]
Please check this notebook.
https://github.com/manashmndl/DeadSimpleSpeechRecognizer/blob/master/DeadSimpleSpeechRecognition.ipynb
