### ISSUE TITLE
regarding `wave, sr = librosa.load(file_path, mono=True, sr=None)     wave = wave[::3]`

### ISSUE THREAD

**Issue by StanSilas** [manashmndl/DeadSimpleSpeechRecognizer#5]
```
def wav2mfcc(file_path, max_pad_len=11):
    wave, sr = librosa.load(file_path, mono=True, sr=None)
    wave = wave[::3]
    mfcc = librosa.feature.mfcc(wave, sr=16000)
    pad_width = max_pad_len - mfcc.shape[1]
    mfcc = np.pad(mfcc, pad_width=((0, 0), (0, pad_width)), mode='constant')
    return mfcc
```

What is significance of   
`   wave, sr = librosa.load(file_path, mono=True, sr=None)
    wave = wave[::3]`

Q1. how does removing mono = true affect the code.
Q2. what is happeniing here :  wave = wave[::3

**Comment by manashmandal** [comment]
A1. Both channel contain same data, that's why taking audio from single channel makes sense.
A2. 

Try this on python
```python
>>> import numpy as np
>>> x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> x[::3]
array([1, 4, 7])
```

Means I am taking the elements which index are divisible by 3. That's basic list operation. In other words I am downsampling audio.
