### ISSUE TITLE
Hey, i have some questions:

### ISSUE THREAD

**Issue by ngragaei** [manashmndl/DeadSimpleSpeechRecognizer#7]
1- What is the max_len and why it is assigned to 11?
2- What is feature_dim_1 and feature_dim_2?

**Comment by manashmandal** [comment]
1. Cut off length to make all speech signals into fixed size
2. 1st feature dimension, 2nd feature dimension

**Comment by ngragaei** [comment]
1- How to choose this cut off length?
2- Can i change them?
Thanks

**Comment by manashmandal** [comment]
1. Just change this code `pad_sequences(mfcc_vector, maxlen=DESIRED_CUTOFF_LENGTH)`
2. You can't change them, the feature dimensions are fixed, check out `librosa` library for more details.

Thanks!
