### ISSUE TITLE
regarding #   if (max_len > mfcc.shape[1]):         pad_width = max_len - mfcc.shape[1]         mfcc = np.pad(mfcc, pad_width=((0, 0), (0, pad_width)), mode='constant')     else:         mfcc = mfcc[:, :max_len]

### ISSUE THREAD

**Issue by saurav993** [manashmndl/DeadSimpleSpeechRecognizer#9]
After performing padding operation, we get the shape of MFCC  as (20, 11). But if the dataset has audio files longer suppose of 24sec and MFCC yields a  shape (20, 2300), here most of the audio files(frames) will be cut off. So is there any way I can get the MFCC feature of an audio file of multiple frames.

**Comment by manashmandal** [comment]
Sorry, didn't understand your question.
